# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
# These limits are taken from https://support.franka.de/docs/control_parameters.html

default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

joint_limits:
  panda_joint1:
    max_position: 2.8973
    min_position: -2.8973
    has_velocity_limits: true
    max_velocity: 2.1750
    has_acceleration_limits: true
    max_acceleration: 15.0
  panda_joint2:
    max_position: 1.7628
    min_position: -1.7628
    has_velocity_limits: true
    max_velocity: 2.1750
    has_acceleration_limits: true
    max_acceleration: 7.5
  panda_joint3:
    max_position: 2.8973
    min_position: -2.8973
    has_velocity_limits: true
    max_velocity: 2.1750
    has_acceleration_limits: true
    max_acceleration: 10.0
  panda_joint4:
    max_position: -0.0698
    min_position: -3.0718
    has_velocity_limits: true
    max_velocity: 12.5
    has_acceleration_limits: true
    max_acceleration: 12.5
  panda_joint5:
    max_position: 2.8973
    min_position: -2.8973
    has_velocity_limits: true
    max_velocity: 2.6100
    has_acceleration_limits: true
    max_acceleration: 15.0
  panda_joint6:
    max_position: 3.7525
    min_position: -0.0175
    has_velocity_limits: true
    max_velocity: 2.6100
    has_acceleration_limits: true
    max_acceleration: 20.0
  panda_joint7:
    max_position: 2.8973
    min_position: -2.8973
    has_velocity_limits: true
    max_velocity: 2.6100
    has_acceleration_limits: true
    max_acceleration: 20.0
  panda_finger_joint1:
    max_position: 0.04
    min_position: 0.00
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: true
    max_acceleration: 20.0
  panda_finger_joint2:
    max_position: 0.04
    min_position: 0.00
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: true
    max_acceleration: 20.0
